<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="htmlDoc" nsURI="http://www.example.org/htmlDoc" nsPrefix="htmlDoc">
  <eClassifiers xsi:type="ecore:EClass" name="DifiForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SkjemaID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//FormStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepTitle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElements" upperBound="-1"
        eType="#//HtmlElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HtmlElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HtmlLabel" eSuperTypes="#//HtmlElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for" lowerBound="1" eType="#//HtmlInput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HtmlInput" eSuperTypes="#//HtmlElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="text"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelledBy" lowerBound="1"
        eType="#//HtmlLabel"/>
  </eClassifiers>
</ecore:EPackage>
