/**
 *
 * $Id$
 */
package no.hib.masters.model.htmldoc.htmlDoc.validation;

import no.hib.masters.model.htmldoc.htmlDoc.HtmlLabel;


/**
 * A sample validator interface for {@link no.hib.masters.model.htmldoc.htmlDoc.HtmlInput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HtmlInputValidator {
	boolean validate();

	boolean validateType(String value);

	boolean validateLabelledBy(HtmlLabel value);
}
