/**
 *
 * $Id$
 */
package no.hib.masters.model.htmldoc.htmlDoc.validation;

import no.hib.masters.model.htmldoc.htmlDoc.HtmlInput;

/**
 * A sample validator interface for {@link no.hib.masters.model.htmldoc.htmlDoc.HtmlLabel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HtmlLabelValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateFor(HtmlInput value);
}
