/**
 *
 * $Id$
 */
package model.validation;

import model.CssStyle;
import model.FormElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link model.FormStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormStepValidator {
	boolean validate();

	boolean validateStepTitle(String value);
	boolean validateFormElements(EList<FormElement> value);
	boolean validateStepStyle(EList<CssStyle> value);
}
