/**
 *
 * $Id$
 */
package model.validation;

import model.CssStyle;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link model.FormElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormElementValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateID(String value);
	boolean validateElementStyle(EList<CssStyle> value);
}
